//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEditor;
using System.Collections;

namespace Spriter2UnityDX
{
	[CustomEditor(typeof(S2USettings))]
	public class S2USettingsEditor : Editor
	{
		public override void OnInspectorGUI ()
		{
			DrawDefaultInspector ();
		
			S2USettings myScript = (S2USettings)target;
			if (GUILayout.Button ("Refresh prefab")) {
				RefeshPrefabSprite ();
			}
		}


		public void RefeshPrefabSprite ()
		{
			GameObject prefab = S2USettings.Settings.prefab;
			ScmlFollower scmlFollower = new ScmlFollower ();
			scmlFollower.Build ();

			if (prefab == null) {
				Debug.LogErrorFormat ("No prefab selected");
				return;
			}

			TextureController[] children = prefab.transform.GetComponentsInChildren<TextureController> (true);
			for (int i =0; i < children.Length; i ++) {
				children [i].Sprites = scmlFollower.sprites [children [i].folder].ToArray ();
			}
		}
	}

}
